apiVersion: v1
kind: Service
metadata:
  labels:
    app: beyond-bookmarks-api-service
  name: beyond-bookmarks-api-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: beyond-bookmarks-api
  sessionAffinity: None
  type: ClusterIP